# Generated by Django 5.2.15 on 2026-06-22 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('HOSPITAL', 'Hôpital'), ('HEALTH_CENTER', 'Centre de santé'), ('CLINIC', 'Clinique'), ('PHARMACY', 'Pharmacie'), ('OTHER', 'Autre')], max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'établissement',
                'verbose_name_plural': 'établissements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserFacilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='facilities.facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facility_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'affectation établissement',
                'verbose_name_plural': 'affectations établissement',
            },
        ),
        migrations.CreateModel(
            name='FacilityService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('active', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['name'],
                'unique_together': {('facility', 'name')},
            },
        ),
    ]
