# Generated by Django 5.2.15 on 2026-06-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('MINISTRY_SUPERVISOR', 'Superviseur ministère'), ('HOSPITAL_MANAGER', 'Responsable hôpital'), ('FACILITY_AGENT', "Agent d'établissement")], max_length=30),
        ),
    ]
