# Generated by Django 5.2.15 on 2026-06-22 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'catégorie de plainte',
                'verbose_name_plural': 'catégories de plainte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('submission_type', models.CharField(choices=[('ANONYMOUS', 'Anonyme'), ('CONFIDENTIAL', 'Confidentiel'), ('IDENTIFIED', 'Identifié')], max_length=20)),
                ('complaint_type', models.CharField(choices=[('COMPLAINT', 'Plainte'), ('SUGGESTION', 'Suggestion'), ('APPRECIATION', 'Félicitation')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_date', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('HIGH', 'Élevée'), ('URGENT', 'Urgente')], max_length=20)),
                ('current_status', models.CharField(choices=[('RECEIVED', 'Reçue'), ('UNDER_REVIEW', 'En examen'), ('IN_PROGRESS', 'En cours'), ('WAITING_INFO', "En attente d'informations"), ('RESOLVED', 'Résolue'), ('REJECTED', 'Rejetée'), ('CLOSED', 'Clôturée')], default='RECEIVED', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('EMAIL', 'E-mail'), ('PHONE', 'Téléphone'), ('SMS', 'SMS')], max_length=30)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='facilities.facility')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='facilities.facilityservice')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.complaintcategory')),
            ],
            options={
                'verbose_name': 'plainte',
                'verbose_name_plural': 'plaintes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_assignments', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'affectation de plainte',
                'verbose_name_plural': 'affectations de plainte',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaints/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'pièce jointe',
                'verbose_name_plural': 'pièces jointes',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_comments', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'commentaire interne',
                'verbose_name_plural': 'commentaires internes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(choices=[('RECEIVED', 'Reçue'), ('UNDER_REVIEW', 'En examen'), ('IN_PROGRESS', 'En cours'), ('WAITING_INFO', "En attente d'informations"), ('RESOLVED', 'Résolue'), ('REJECTED', 'Rejetée'), ('CLOSED', 'Clôturée')], max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_status_changes', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'historique de statut',
                'verbose_name_plural': 'historiques de statut',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['reference'], name='complaints__referen_68a7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['current_status'], name='complaints__current_b0f980_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['facility', 'current_status'], name='complaints__facilit_32c56a_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['-created_at'], name='complaints__created_a26128_idx'),
        ),
    ]
