# Generated by Django 5.2.15 on 2026-06-22 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='reported_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_against_agent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='reported_agent_name',
            field=models.CharField(blank=True, help_text="Nom de l'agent visé si non enregistré dans le système", max_length=255),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='submitter_profile',
            field=models.CharField(choices=[('CITIZEN', 'Usager / citoyen'), ('FACILITY_AGENT', "Agent d'établissement")], default='CITIZEN', max_length=20),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['submitter_profile'], name='complaints__submitt_d6ddff_idx'),
        ),
    ]
