# Generated by Django 5.2.15 on 2026-06-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_reported_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='requested_actions',
            field=models.TextField(blank=True, help_text='Mesures ou actions que le plaignant souhaite voir prises (optionnel).', verbose_name='actions souhaitées'),
        ),
    ]
