# Generated by Django 5.2.15 on 2026-06-23 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_complaint_reported_agent_and_more'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UssdSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('step', models.CharField(default='HOME', max_length=30)),
                ('page', models.PositiveIntegerField(default=0)),
                ('complaint_type', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='complaints.complaintcategory')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='complaints.complaint')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facility')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facilityservice')),
            ],
            options={
                'verbose_name': 'session USSD',
                'verbose_name_plural': 'sessions USSD',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['session_id'], name='complaints__session_5844a6_idx')],
            },
        ),
    ]
