# Generated by Django 5.2.15 on 2026-06-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaint_requested_actions'),
        ('complaints', '0003_ussdsession'),
    ]

    operations = [
    ]
