# Generated by Django 5.2.15 on 2026-06-24 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0003_ussdsession'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=64, unique=True)),
                ('step', models.CharField(default='ASK_TYPE', max_length=30)),
                ('page', models.PositiveIntegerField(default=0)),
                ('anonymous', models.BooleanField(default=False)),
                ('complaint_type', models.CharField(blank=True, max_length=20)),
                ('severity', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('transcription_ia', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='complaints.complaintcategory')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='complaints.complaint')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facility')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='facilities.facilityservice')),
            ],
            options={
                'verbose_name': 'session WhatsApp',
                'verbose_name_plural': 'sessions WhatsApp',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['chat_id'], name='whatsapp_wh_chat_id_a25323_idx')],
            },
        ),
    ]
