# Generated by Django 5.2.15 on 2026-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsession',
            name='language',
            field=models.CharField(default='fr', max_length=5),
        ),
        migrations.AlterField(
            model_name='whatsappsession',
            name='step',
            field=models.CharField(default='ASK_LANG', max_length=30),
        ),
    ]
