# Generated by Django 5.2.15 on 2026-06-23 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('COMPLAINT_CREATED', 'Signalement enregistré'), ('COMPLAINT_STATUS_CHANGED', 'Statut modifié'), ('COMPLAINT_REJECTED', 'Plainte rejetée'), ('COMPLAINT_COMMENT_ADDED', 'Commentaire interne ajouté')], max_length=40)),
                ('resource_type', models.CharField(choices=[('complaint', 'Plainte')], max_length=30)),
                ('resource_id', models.CharField(max_length=64)),
                ('resource_label', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='facilities.facility')),
            ],
            options={
                'verbose_name': 'entrée de journal',
                'verbose_name_plural': "journal d'audit",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_6e540c_idx'), models.Index(fields=['facility', '-created_at'], name='audit_audit_facilit_b41d3d_idx'), models.Index(fields=['resource_type', 'resource_id'], name='audit_audit_resourc_2a3aef_idx'), models.Index(fields=['action'], name='audit_audit_action_86e815_idx')],
            },
        ),
    ]
